- hosts: webservers
  vars:
    nginx_port: 8282
    root_dir: /usr/share/nginx/html
    server_text: "This is server {{ server_name }}!"
    deployed_date: "{{ ansible_date_time.date}} {{ ansible_date_time.time }}"
  remote_user: vagrant
  tasks:

    - name: Gather the package facats
      ansible.builtin.package_facts:
        manager: auto

    - name: install nginx
      become: yes
      ansible.builtin.dnf:
        name: nginx
        state: latest
        update_cache: yes


    - name: enable crb repo
      become: yes
      community.general.dnf_config_manager:
        name: crb
        state: enabled

    - name: install epel repo
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - epel-release
        - epel-next-release

    - name: install cowsay
      become: yes
      ansible.builtin.dnf:
        name: cowsay
        state: latest
        update_cache: yes

    - name: cowsay
      ansible.builtin.shell: cowsay "This is server {{ server_name }}"
      register: cowsay
      when: "'cowsay' in ansible_facts.packages"


    - name: update nginx config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

    - name: Wrap host root index file
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{root_dir}}/index.html"
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
        enabled: yes
      become: yes
