- hosts: webservers
  vars:
    nginx_port: 8282
    root_dir: /usr/share/nginx/html
  remote_user: vagrant
  tasks:

    - name: install nginx
      become: yes
      ansible.builtin.dnf:
        name: nginx
        state: latest
        update_cache: yes

    - name: update nginx config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

    - name: Wrap host root index file
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{root_dir}}/index.html"
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
