- hosts: webservers
  gather_facts: no
  remote_user: vagrant
  tasks:
    - name: install git 
      become: yes
      ansible.builtin.dnf:
        name: git
        state: present
        update_cache: yes
