- hosts: servers
  remote_user: vagrant
  tasks:
    - name: Reboot system
      become: yes
      block:
      - shell: sleep 5 && init 6
        async: 300
        poll: 0
        ignore_errors: true
    - name: Wait for system come back online
      wait_for_connection:
        delay: 60
        timeout: 300
