- hosts: developers
  vars:
    user_name: biatl0n
    user_password: duffy
    user_shell: /bin/bash
    user_email: biatl0n@yandex.ru
  roles:
    - role: geerlingguy.postgresql
      become: yes
      vars:
        postgresql_user_name: vagrant
    - role: geerlingguy.git
      become: yes
    - role: geerlingguy.nodejs
      become: yes
    - role: devEnvInit
      become: yes
  remote_user: vagrant
